/* eslint-disable */
module.exports = /*
 * Generated by PEG.js 0.10.0.
 *
 * http://pegjs.org/
 */
	(function() {
		function peg$subclass(child, parent) {
			function ctor() { this.constructor = child; }
			ctor.prototype = parent.prototype;
			child.prototype = new ctor();
		}

		function peg$SyntaxError(message, expected, found, location) {
			this.message  = message;
			this.expected = expected;
			this.found    = found;
			this.location = location;
			this.name     = "SyntaxError";

			if (typeof Error.captureStackTrace === "function") {
				Error.captureStackTrace(this, peg$SyntaxError);
			}
		}

		peg$subclass(peg$SyntaxError, Error);

		peg$SyntaxError.buildMessage = function(expected, found) {
			var DESCRIBE_EXPECTATION_FNS = {
				literal: function(expectation) {
					return "\"" + literalEscape(expectation.text) + "\"";
				},

				"class": function(expectation) {
					var escapedParts = "",
						i;

					for (i = 0; i < expectation.parts.length; i++) {
						escapedParts += expectation.parts[i] instanceof Array
							? classEscape(expectation.parts[i][0]) + "-" + classEscape(expectation.parts[i][1])
							: classEscape(expectation.parts[i]);
					}

					return "[" + (expectation.inverted ? "^" : "") + escapedParts + "]";
				},

				any: function(expectation) {
					return "any character";
				},

				end: function(expectation) {
					return "end of input";
				},

				other: function(expectation) {
					return expectation.description;
				}
			};

			function hex(ch) {
				return ch.charCodeAt(0).toString(16).toUpperCase();
			}

			function literalEscape(s) {
				return s
					.replace(/\\/g, '\\\\')
					.replace(/"/g,  '\\"')
					.replace(/\0/g, '\\0')
					.replace(/\t/g, '\\t')
					.replace(/\n/g, '\\n')
					.replace(/\r/g, '\\r')
					.replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
					.replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
			}

			function classEscape(s) {
				return s
					.replace(/\\/g, '\\\\')
					.replace(/\]/g, '\\]')
					.replace(/\^/g, '\\^')
					.replace(/-/g,  '\\-')
					.replace(/\0/g, '\\0')
					.replace(/\t/g, '\\t')
					.replace(/\n/g, '\\n')
					.replace(/\r/g, '\\r')
					.replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
					.replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
			}

			function describeExpectation(expectation) {
				return DESCRIBE_EXPECTATION_FNS[expectation.type](expectation);
			}

			function describeExpected(expected) {
				var descriptions = new Array(expected.length),
					i, j;

				for (i = 0; i < expected.length; i++) {
					descriptions[i] = describeExpectation(expected[i]);
				}

				descriptions.sort();

				if (descriptions.length > 0) {
					for (i = 1, j = 1; i < descriptions.length; i++) {
						if (descriptions[i - 1] !== descriptions[i]) {
							descriptions[j] = descriptions[i];
							j++;
						}
					}
					descriptions.length = j;
				}

				switch (descriptions.length) {
					case 1:
						return descriptions[0];

					case 2:
						return descriptions[0] + " or " + descriptions[1];

					default:
						return descriptions.slice(0, -1).join(", ")
							+ ", or "
							+ descriptions[descriptions.length - 1];
				}
			}

			function describeFound(found) {
				return found ? "\"" + literalEscape(found) + "\"" : "end of input";
			}

			return "Expected " + describeExpected(expected) + " but " + describeFound(found) + " found.";
		};

		function peg$parse(input, options) {
			options = options !== void 0 ? options : {};

			var peg$FAILED = {},

				peg$startRuleFunctions = { Document: peg$parseDocument },
				peg$startRuleFunction  = peg$parseDocument,

				peg$c0 = function(l) { return l },
				peg$c1 = function(ls, l) { return ls.concat( l ) },
				peg$c2 = function(ts) {
					const tokens = ts.reduce(
						function(out, next) {
							return typeof next === 'string' && typeof out[1] === 'string'
								? [ out[0].slice(0, -1).concat( out[0].slice(-1).concat( next ).join('') ), next ]
								: [ out[0].concat( next ), next ];
						},
						[[], undefined]
					)

					return tokens[0].map( function( token ) {
						const value = typeof token === 'string'
							? { type: 'text', text: token }
							: token;

						return Object.assign( value, { location: location() } )
					} )
				},
				peg$c3 = "#",
				peg$c4 = peg$literalExpectation("#", false),
				peg$c5 = /^[^\n]/,
				peg$c6 = peg$classExpectation(["\n"], true, false),
				peg$c7 = function(l, h) { return { type: 'header', level: l.length, text: h.join(''), location: location() } },
				peg$c8 = "://",
				peg$c9 = peg$literalExpectation("://", false),
				peg$c10 = "/",
				peg$c11 = peg$literalExpectation("/", false),
				peg$c12 = function(scheme, host, slash, path) { return {
					type: 'link',
					text: '',
					href: {
						url: scheme + '://' + [ host, slash, path ].join(''),
						location: location()
					},
					location: location()
				} },
				peg$c13 = /^[a-z]/,
				peg$c14 = peg$classExpectation([["a", "z"]], false, false),
				peg$c15 = /^[a-z0-9+.\-]/,
				peg$c16 = peg$classExpectation([["a", "z"], ["0", "9"], "+", ".", "-"], false, false),
				peg$c17 = function(s, ss) { return s + ss.join('') },
				peg$c18 = ".",
				peg$c19 = peg$literalExpectation(".", false),
				peg$c20 = function(pp, p) { return p },
				peg$c21 = function(pp, ps) { return [pp].concat( ps ).join('.') },
				peg$c22 = /^[0-9a-z\-_~]/,
				peg$c23 = peg$classExpectation([["0", "9"], ["a", "z"], "-", "_", "~"], false, false),
				peg$c24 = function(cs) { return cs.join('') },
				peg$c25 = function(p, t) { return [p, t].join('') },
				peg$c26 = function(ps) { return ps.join('') },
				peg$c27 = function(c, ccs) { return '.' + ccs.join('') },
				peg$c28 = function(c, cs) { return [c.join('')].concat( cs ).join('') },
				peg$c29 = /^[a-z0-9\-_~]/,
				peg$c30 = peg$classExpectation([["a", "z"], ["0", "9"], "-", "_", "~"], false, false),
				peg$c31 = "<a",
				peg$c32 = peg$literalExpectation("<a", false),
				peg$c33 = /^[ ]/,
				peg$c34 = peg$classExpectation([" "], false, false),
				peg$c35 = function(a) { return a },
				peg$c36 = ">",
				peg$c37 = peg$literalExpectation(">", false),
				peg$c38 = /^[^<]/,
				peg$c39 = peg$classExpectation(["<"], true, false),
				peg$c40 = "</a>",
				peg$c41 = peg$literalExpectation("</a>", false),
				peg$c42 = function(as, a, text) { return {
					type: 'link',
					text: text.join(''),
					href: {
						url: as.concat( a ).find( a => 'href' === a.name ).value,
						location: as.concat( a ).find( a => 'href' === a.name ).location
					}
				} },
				peg$c43 = /^[a-zA-Z]/,
				peg$c44 = peg$classExpectation([["a", "z"], ["A", "Z"]], false, false),
				peg$c45 = "=",
				peg$c46 = peg$literalExpectation("=", false),
				peg$c47 = function(name, v) { return { v: v.s, l: v.l } },
				peg$c48 = function(name, value) { return { name: name.join(''), value: value.v, location: value.l } },
				peg$c49 = "\"",
				peg$c50 = peg$literalExpectation("\"", false),
				peg$c51 = /^[^"]/,
				peg$c52 = peg$classExpectation(["\""], true, false),
				peg$c53 = function(s) { return { v: s.join(''), l: location() } },
				peg$c54 = function(string) { return { s: string.v, l: string.l } },
				peg$c55 = "[",
				peg$c56 = peg$literalExpectation("[", false),
				peg$c57 = /^[^\]]/,
				peg$c58 = peg$classExpectation(["]"], true, false),
				peg$c59 = "](",
				peg$c60 = peg$literalExpectation("](", false),
				peg$c61 = /^[^)]/,
				peg$c62 = peg$classExpectation([")"], true, false),
				peg$c63 = function(text, url) { return { url: url, location: location() } },
				peg$c64 = ")",
				peg$c65 = peg$literalExpectation(")", false),
				peg$c66 = function(text, href) { return {
					type: 'link',
					text: text.join( '' ),
					href: { url: href.url.join( '' ), location: href.location }
				} },
				peg$c67 = /^[\n]/,
				peg$c68 = peg$classExpectation(["\n"], false, false),

				peg$currPos          = 0,
				peg$savedPos         = 0,
				peg$posDetailsCache  = [{ line: 1, column: 1 }],
				peg$maxFailPos       = 0,
				peg$maxFailExpected  = [],
				peg$silentFails      = 0,

				peg$result;

			if ("startRule" in options) {
				if (!(options.startRule in peg$startRuleFunctions)) {
					throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");
				}

				peg$startRuleFunction = peg$startRuleFunctions[options.startRule];
			}

			function text() {
				return input.substring(peg$savedPos, peg$currPos);
			}

			function location() {
				return peg$computeLocation(peg$savedPos, peg$currPos);
			}

			function expected(description, location) {
				location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

				throw peg$buildStructuredError(
					[peg$otherExpectation(description)],
					input.substring(peg$savedPos, peg$currPos),
					location
				);
			}

			function error(message, location) {
				location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

				throw peg$buildSimpleError(message, location);
			}

			function peg$literalExpectation(text, ignoreCase) {
				return { type: "literal", text: text, ignoreCase: ignoreCase };
			}

			function peg$classExpectation(parts, inverted, ignoreCase) {
				return { type: "class", parts: parts, inverted: inverted, ignoreCase: ignoreCase };
			}

			function peg$anyExpectation() {
				return { type: "any" };
			}

			function peg$endExpectation() {
				return { type: "end" };
			}

			function peg$otherExpectation(description) {
				return { type: "other", description: description };
			}

			function peg$computePosDetails(pos) {
				var details = peg$posDetailsCache[pos], p;

				if (details) {
					return details;
				} else {
					p = pos - 1;
					while (!peg$posDetailsCache[p]) {
						p--;
					}

					details = peg$posDetailsCache[p];
					details = {
						line:   details.line,
						column: details.column
					};

					while (p < pos) {
						if (input.charCodeAt(p) === 10) {
							details.line++;
							details.column = 1;
						} else {
							details.column++;
						}

						p++;
					}

					peg$posDetailsCache[pos] = details;
					return details;
				}
			}

			function peg$computeLocation(startPos, endPos) {
				var startPosDetails = peg$computePosDetails(startPos),
					endPosDetails   = peg$computePosDetails(endPos);

				return {
					start: {
						offset: startPos,
						line:   startPosDetails.line,
						column: startPosDetails.column
					},
					end: {
						offset: endPos,
						line:   endPosDetails.line,
						column: endPosDetails.column
					}
				};
			}

			function peg$fail(expected) {
				if (peg$currPos < peg$maxFailPos) { return; }

				if (peg$currPos > peg$maxFailPos) {
					peg$maxFailPos = peg$currPos;
					peg$maxFailExpected = [];
				}

				peg$maxFailExpected.push(expected);
			}

			function peg$buildSimpleError(message, location) {
				return new peg$SyntaxError(message, null, null, location);
			}

			function peg$buildStructuredError(expected, found, location) {
				return new peg$SyntaxError(
					peg$SyntaxError.buildMessage(expected, found),
					expected,
					found,
					location
				);
			}

			function peg$parseDocument() {
				var s0, s1, s2, s3, s4;

				s0 = peg$currPos;
				s1 = [];
				s2 = peg$currPos;
				s3 = peg$parseLine();
				if (s3 !== peg$FAILED) {
					s4 = peg$parseNewline();
					if (s4 !== peg$FAILED) {
						peg$savedPos = s2;
						s3 = peg$c0(s3);
						s2 = s3;
					} else {
						peg$currPos = s2;
						s2 = peg$FAILED;
					}
				} else {
					peg$currPos = s2;
					s2 = peg$FAILED;
				}
				while (s2 !== peg$FAILED) {
					s1.push(s2);
					s2 = peg$currPos;
					s3 = peg$parseLine();
					if (s3 !== peg$FAILED) {
						s4 = peg$parseNewline();
						if (s4 !== peg$FAILED) {
							peg$savedPos = s2;
							s3 = peg$c0(s3);
							s2 = s3;
						} else {
							peg$currPos = s2;
							s2 = peg$FAILED;
						}
					} else {
						peg$currPos = s2;
						s2 = peg$FAILED;
					}
				}
				if (s1 !== peg$FAILED) {
					s2 = peg$parseLine();
					if (s2 !== peg$FAILED) {
						peg$savedPos = s0;
						s1 = peg$c1(s1, s2);
						s0 = s1;
					} else {
						peg$currPos = s0;
						s0 = peg$FAILED;
					}
				} else {
					peg$currPos = s0;
					s0 = peg$FAILED;
				}

				return s0;
			}

			function peg$parseLine() {
				var s0, s1, s2;

				s0 = peg$parseHeader();
				if (s0 === peg$FAILED) {
					s0 = peg$currPos;
					s1 = [];
					s2 = peg$parseToken();
					while (s2 !== peg$FAILED) {
						s1.push(s2);
						s2 = peg$parseToken();
					}
					if (s1 !== peg$FAILED) {
						peg$savedPos = s0;
						s1 = peg$c2(s1);
					}
					s0 = s1;
				}

				return s0;
			}

			function peg$parseHeader() {
				var s0, s1, s2, s3;

				s0 = peg$currPos;
				s1 = [];
				if (input.charCodeAt(peg$currPos) === 35) {
					s2 = peg$c3;
					peg$currPos++;
				} else {
					s2 = peg$FAILED;
					if (peg$silentFails === 0) { peg$fail(peg$c4); }
				}
				if (s2 !== peg$FAILED) {
					while (s2 !== peg$FAILED) {
						s1.push(s2);
						if (input.charCodeAt(peg$currPos) === 35) {
							s2 = peg$c3;
							peg$currPos++;
						} else {
							s2 = peg$FAILED;
							if (peg$silentFails === 0) { peg$fail(peg$c4); }
						}
					}
				} else {
					s1 = peg$FAILED;
				}
				if (s1 !== peg$FAILED) {
					s2 = [];
					if (peg$c5.test(input.charAt(peg$currPos))) {
						s3 = input.charAt(peg$currPos);
						peg$currPos++;
					} else {
						s3 = peg$FAILED;
						if (peg$silentFails === 0) { peg$fail(peg$c6); }
					}
					while (s3 !== peg$FAILED) {
						s2.push(s3);
						if (peg$c5.test(input.charAt(peg$currPos))) {
							s3 = input.charAt(peg$currPos);
							peg$currPos++;
						} else {
							s3 = peg$FAILED;
							if (peg$silentFails === 0) { peg$fail(peg$c6); }
						}
					}
					if (s2 !== peg$FAILED) {
						peg$savedPos = s0;
						s1 = peg$c7(s1, s2);
						s0 = s1;
					} else {
						peg$currPos = s0;
						s0 = peg$FAILED;
					}
				} else {
					peg$currPos = s0;
					s0 = peg$FAILED;
				}

				return s0;
			}

			function peg$parseToken() {
				var s0;

				s0 = peg$parseHtmlLink();
				if (s0 === peg$FAILED) {
					s0 = peg$parseMarkdownLink();
					if (s0 === peg$FAILED) {
						s0 = peg$parseUrl();
						if (s0 === peg$FAILED) {
							if (peg$c5.test(input.charAt(peg$currPos))) {
								s0 = input.charAt(peg$currPos);
								peg$currPos++;
							} else {
								s0 = peg$FAILED;
								if (peg$silentFails === 0) { peg$fail(peg$c6); }
							}
						}
					}
				}

				return s0;
			}

			function peg$parseUrl() {
				var s0, s1, s2, s3, s4, s5;

				s0 = peg$currPos;
				s1 = peg$parseUrlScheme();
				if (s1 !== peg$FAILED) {
					if (input.substr(peg$currPos, 3) === peg$c8) {
						s2 = peg$c8;
						peg$currPos += 3;
					} else {
						s2 = peg$FAILED;
						if (peg$silentFails === 0) { peg$fail(peg$c9); }
					}
					if (s2 !== peg$FAILED) {
						s3 = peg$parseUrlHost();
						if (s3 !== peg$FAILED) {
							if (input.charCodeAt(peg$currPos) === 47) {
								s4 = peg$c10;
								peg$currPos++;
							} else {
								s4 = peg$FAILED;
								if (peg$silentFails === 0) { peg$fail(peg$c11); }
							}
							if (s4 === peg$FAILED) {
								s4 = null;
							}
							if (s4 !== peg$FAILED) {
								s5 = peg$parseUrlPath();
								if (s5 === peg$FAILED) {
									s5 = null;
								}
								if (s5 !== peg$FAILED) {
									peg$savedPos = s0;
									s1 = peg$c12(s1, s3, s4, s5);
									s0 = s1;
								} else {
									peg$currPos = s0;
									s0 = peg$FAILED;
								}
							} else {
								peg$currPos = s0;
								s0 = peg$FAILED;
							}
						} else {
							peg$currPos = s0;
							s0 = peg$FAILED;
						}
					} else {
						peg$currPos = s0;
						s0 = peg$FAILED;
					}
				} else {
					peg$currPos = s0;
					s0 = peg$FAILED;
				}

				return s0;
			}

			function peg$parseUrlScheme() {
				var s0, s1, s2, s3;

				s0 = peg$currPos;
				if (peg$c13.test(input.charAt(peg$currPos))) {
					s1 = input.charAt(peg$currPos);
					peg$currPos++;
				} else {
					s1 = peg$FAILED;
					if (peg$silentFails === 0) { peg$fail(peg$c14); }
				}
				if (s1 !== peg$FAILED) {
					s2 = [];
					if (peg$c15.test(input.charAt(peg$currPos))) {
						s3 = input.charAt(peg$currPos);
						peg$currPos++;
					} else {
						s3 = peg$FAILED;
						if (peg$silentFails === 0) { peg$fail(peg$c16); }
					}
					if (s3 !== peg$FAILED) {
						while (s3 !== peg$FAILED) {
							s2.push(s3);
							if (peg$c15.test(input.charAt(peg$currPos))) {
								s3 = input.charAt(peg$currPos);
								peg$currPos++;
							} else {
								s3 = peg$FAILED;
								if (peg$silentFails === 0) { peg$fail(peg$c16); }
							}
						}
					} else {
						s2 = peg$FAILED;
					}
					if (s2 !== peg$FAILED) {
						peg$savedPos = s0;
						s1 = peg$c17(s1, s2);
						s0 = s1;
					} else {
						peg$currPos = s0;
						s0 = peg$FAILED;
					}
				} else {
					peg$currPos = s0;
					s0 = peg$FAILED;
				}

				return s0;
			}

			function peg$parseUrlHost() {
				var s0, s1, s2, s3, s4, s5;

				s0 = peg$currPos;
				s1 = peg$parseUrlHostPart();
				if (s1 !== peg$FAILED) {
					s2 = [];
					s3 = peg$currPos;
					if (input.charCodeAt(peg$currPos) === 46) {
						s4 = peg$c18;
						peg$currPos++;
					} else {
						s4 = peg$FAILED;
						if (peg$silentFails === 0) { peg$fail(peg$c19); }
					}
					if (s4 !== peg$FAILED) {
						s5 = peg$parseUrlHostPart();
						if (s5 !== peg$FAILED) {
							peg$savedPos = s3;
							s4 = peg$c20(s1, s5);
							s3 = s4;
						} else {
							peg$currPos = s3;
							s3 = peg$FAILED;
						}
					} else {
						peg$currPos = s3;
						s3 = peg$FAILED;
					}
					while (s3 !== peg$FAILED) {
						s2.push(s3);
						s3 = peg$currPos;
						if (input.charCodeAt(peg$currPos) === 46) {
							s4 = peg$c18;
							peg$currPos++;
						} else {
							s4 = peg$FAILED;
							if (peg$silentFails === 0) { peg$fail(peg$c19); }
						}
						if (s4 !== peg$FAILED) {
							s5 = peg$parseUrlHostPart();
							if (s5 !== peg$FAILED) {
								peg$savedPos = s3;
								s4 = peg$c20(s1, s5);
								s3 = s4;
							} else {
								peg$currPos = s3;
								s3 = peg$FAILED;
							}
						} else {
							peg$currPos = s3;
							s3 = peg$FAILED;
						}
					}
					if (s2 !== peg$FAILED) {
						peg$savedPos = s0;
						s1 = peg$c21(s1, s2);
						s0 = s1;
					} else {
						peg$currPos = s0;
						s0 = peg$FAILED;
					}
				} else {
					peg$currPos = s0;
					s0 = peg$FAILED;
				}

				return s0;
			}

			function peg$parseUrlHostPart() {
				var s0, s1, s2;

				s0 = peg$currPos;
				s1 = [];
				if (peg$c22.test(input.charAt(peg$currPos))) {
					s2 = input.charAt(peg$currPos);
					peg$currPos++;
				} else {
					s2 = peg$FAILED;
					if (peg$silentFails === 0) { peg$fail(peg$c23); }
				}
				if (s2 !== peg$FAILED) {
					while (s2 !== peg$FAILED) {
						s1.push(s2);
						if (peg$c22.test(input.charAt(peg$currPos))) {
							s2 = input.charAt(peg$currPos);
							peg$currPos++;
						} else {
							s2 = peg$FAILED;
							if (peg$silentFails === 0) { peg$fail(peg$c23); }
						}
					}
				} else {
					s1 = peg$FAILED;
				}
				if (s1 !== peg$FAILED) {
					peg$savedPos = s0;
					s1 = peg$c24(s1);
				}
				s0 = s1;

				return s0;
			}

			function peg$parseUrlPath() {
				var s0, s1, s2, s3, s4;

				s0 = peg$currPos;
				s1 = [];
				s2 = peg$currPos;
				s3 = peg$parseUrlPathPart();
				if (s3 !== peg$FAILED) {
					if (input.charCodeAt(peg$currPos) === 47) {
						s4 = peg$c10;
						peg$currPos++;
					} else {
						s4 = peg$FAILED;
						if (peg$silentFails === 0) { peg$fail(peg$c11); }
					}
					if (s4 === peg$FAILED) {
						s4 = null;
					}
					if (s4 !== peg$FAILED) {
						peg$savedPos = s2;
						s3 = peg$c25(s3, s4);
						s2 = s3;
					} else {
						peg$currPos = s2;
						s2 = peg$FAILED;
					}
				} else {
					peg$currPos = s2;
					s2 = peg$FAILED;
				}
				if (s2 !== peg$FAILED) {
					while (s2 !== peg$FAILED) {
						s1.push(s2);
						s2 = peg$currPos;
						s3 = peg$parseUrlPathPart();
						if (s3 !== peg$FAILED) {
							if (input.charCodeAt(peg$currPos) === 47) {
								s4 = peg$c10;
								peg$currPos++;
							} else {
								s4 = peg$FAILED;
								if (peg$silentFails === 0) { peg$fail(peg$c11); }
							}
							if (s4 === peg$FAILED) {
								s4 = null;
							}
							if (s4 !== peg$FAILED) {
								peg$savedPos = s2;
								s3 = peg$c25(s3, s4);
								s2 = s3;
							} else {
								peg$currPos = s2;
								s2 = peg$FAILED;
							}
						} else {
							peg$currPos = s2;
							s2 = peg$FAILED;
						}
					}
				} else {
					s1 = peg$FAILED;
				}
				if (s1 !== peg$FAILED) {
					peg$savedPos = s0;
					s1 = peg$c26(s1);
				}
				s0 = s1;

				return s0;
			}

			function peg$parseUrlPathPart() {
				var s0, s1, s2, s3, s4, s5, s6;

				s0 = peg$currPos;
				s1 = [];
				s2 = peg$parseUrlPathChar();
				if (s2 !== peg$FAILED) {
					while (s2 !== peg$FAILED) {
						s1.push(s2);
						s2 = peg$parseUrlPathChar();
					}
				} else {
					s1 = peg$FAILED;
				}
				if (s1 !== peg$FAILED) {
					s2 = [];
					s3 = peg$currPos;
					if (input.charCodeAt(peg$currPos) === 46) {
						s4 = peg$c18;
						peg$currPos++;
					} else {
						s4 = peg$FAILED;
						if (peg$silentFails === 0) { peg$fail(peg$c19); }
					}
					if (s4 !== peg$FAILED) {
						s5 = [];
						s6 = peg$parseUrlPathChar();
						if (s6 !== peg$FAILED) {
							while (s6 !== peg$FAILED) {
								s5.push(s6);
								s6 = peg$parseUrlPathChar();
							}
						} else {
							s5 = peg$FAILED;
						}
						if (s5 !== peg$FAILED) {
							peg$savedPos = s3;
							s4 = peg$c27(s1, s5);
							s3 = s4;
						} else {
							peg$currPos = s3;
							s3 = peg$FAILED;
						}
					} else {
						peg$currPos = s3;
						s3 = peg$FAILED;
					}
					while (s3 !== peg$FAILED) {
						s2.push(s3);
						s3 = peg$currPos;
						if (input.charCodeAt(peg$currPos) === 46) {
							s4 = peg$c18;
							peg$currPos++;
						} else {
							s4 = peg$FAILED;
							if (peg$silentFails === 0) { peg$fail(peg$c19); }
						}
						if (s4 !== peg$FAILED) {
							s5 = [];
							s6 = peg$parseUrlPathChar();
							if (s6 !== peg$FAILED) {
								while (s6 !== peg$FAILED) {
									s5.push(s6);
									s6 = peg$parseUrlPathChar();
								}
							} else {
								s5 = peg$FAILED;
							}
							if (s5 !== peg$FAILED) {
								peg$savedPos = s3;
								s4 = peg$c27(s1, s5);
								s3 = s4;
							} else {
								peg$currPos = s3;
								s3 = peg$FAILED;
							}
						} else {
							peg$currPos = s3;
							s3 = peg$FAILED;
						}
					}
					if (s2 !== peg$FAILED) {
						peg$savedPos = s0;
						s1 = peg$c28(s1, s2);
						s0 = s1;
					} else {
						peg$currPos = s0;
						s0 = peg$FAILED;
					}
				} else {
					peg$currPos = s0;
					s0 = peg$FAILED;
				}

				return s0;
			}

			function peg$parseUrlPathChar() {
				var s0;

				if (peg$c29.test(input.charAt(peg$currPos))) {
					s0 = input.charAt(peg$currPos);
					peg$currPos++;
				} else {
					s0 = peg$FAILED;
					if (peg$silentFails === 0) { peg$fail(peg$c30); }
				}

				return s0;
			}

			function peg$parseHtmlLink() {
				var s0, s1, s2, s3, s4, s5, s6, s7, s8;

				s0 = peg$currPos;
				if (input.substr(peg$currPos, 2) === peg$c31) {
					s1 = peg$c31;
					peg$currPos += 2;
				} else {
					s1 = peg$FAILED;
					if (peg$silentFails === 0) { peg$fail(peg$c32); }
				}
				if (s1 !== peg$FAILED) {
					s2 = [];
					if (peg$c33.test(input.charAt(peg$currPos))) {
						s3 = input.charAt(peg$currPos);
						peg$currPos++;
					} else {
						s3 = peg$FAILED;
						if (peg$silentFails === 0) { peg$fail(peg$c34); }
					}
					if (s3 !== peg$FAILED) {
						while (s3 !== peg$FAILED) {
							s2.push(s3);
							if (peg$c33.test(input.charAt(peg$currPos))) {
								s3 = input.charAt(peg$currPos);
								peg$currPos++;
							} else {
								s3 = peg$FAILED;
								if (peg$silentFails === 0) { peg$fail(peg$c34); }
							}
						}
					} else {
						s2 = peg$FAILED;
					}
					if (s2 !== peg$FAILED) {
						s3 = [];
						s4 = peg$currPos;
						s5 = peg$parseHtmlAttribute();
						if (s5 !== peg$FAILED) {
							s6 = [];
							if (peg$c33.test(input.charAt(peg$currPos))) {
								s7 = input.charAt(peg$currPos);
								peg$currPos++;
							} else {
								s7 = peg$FAILED;
								if (peg$silentFails === 0) { peg$fail(peg$c34); }
							}
							if (s7 !== peg$FAILED) {
								while (s7 !== peg$FAILED) {
									s6.push(s7);
									if (peg$c33.test(input.charAt(peg$currPos))) {
										s7 = input.charAt(peg$currPos);
										peg$currPos++;
									} else {
										s7 = peg$FAILED;
										if (peg$silentFails === 0) { peg$fail(peg$c34); }
									}
								}
							} else {
								s6 = peg$FAILED;
							}
							if (s6 !== peg$FAILED) {
								peg$savedPos = s4;
								s5 = peg$c35(s5);
								s4 = s5;
							} else {
								peg$currPos = s4;
								s4 = peg$FAILED;
							}
						} else {
							peg$currPos = s4;
							s4 = peg$FAILED;
						}
						while (s4 !== peg$FAILED) {
							s3.push(s4);
							s4 = peg$currPos;
							s5 = peg$parseHtmlAttribute();
							if (s5 !== peg$FAILED) {
								s6 = [];
								if (peg$c33.test(input.charAt(peg$currPos))) {
									s7 = input.charAt(peg$currPos);
									peg$currPos++;
								} else {
									s7 = peg$FAILED;
									if (peg$silentFails === 0) { peg$fail(peg$c34); }
								}
								if (s7 !== peg$FAILED) {
									while (s7 !== peg$FAILED) {
										s6.push(s7);
										if (peg$c33.test(input.charAt(peg$currPos))) {
											s7 = input.charAt(peg$currPos);
											peg$currPos++;
										} else {
											s7 = peg$FAILED;
											if (peg$silentFails === 0) { peg$fail(peg$c34); }
										}
									}
								} else {
									s6 = peg$FAILED;
								}
								if (s6 !== peg$FAILED) {
									peg$savedPos = s4;
									s5 = peg$c35(s5);
									s4 = s5;
								} else {
									peg$currPos = s4;
									s4 = peg$FAILED;
								}
							} else {
								peg$currPos = s4;
								s4 = peg$FAILED;
							}
						}
						if (s3 !== peg$FAILED) {
							s4 = peg$parseHtmlAttribute();
							if (s4 === peg$FAILED) {
								s4 = null;
							}
							if (s4 !== peg$FAILED) {
								if (input.charCodeAt(peg$currPos) === 47) {
									s5 = peg$c10;
									peg$currPos++;
								} else {
									s5 = peg$FAILED;
									if (peg$silentFails === 0) { peg$fail(peg$c11); }
								}
								if (s5 === peg$FAILED) {
									s5 = null;
								}
								if (s5 !== peg$FAILED) {
									if (input.charCodeAt(peg$currPos) === 62) {
										s6 = peg$c36;
										peg$currPos++;
									} else {
										s6 = peg$FAILED;
										if (peg$silentFails === 0) { peg$fail(peg$c37); }
									}
									if (s6 !== peg$FAILED) {
										s7 = [];
										if (peg$c38.test(input.charAt(peg$currPos))) {
											s8 = input.charAt(peg$currPos);
											peg$currPos++;
										} else {
											s8 = peg$FAILED;
											if (peg$silentFails === 0) { peg$fail(peg$c39); }
										}
										if (s8 !== peg$FAILED) {
											while (s8 !== peg$FAILED) {
												s7.push(s8);
												if (peg$c38.test(input.charAt(peg$currPos))) {
													s8 = input.charAt(peg$currPos);
													peg$currPos++;
												} else {
													s8 = peg$FAILED;
													if (peg$silentFails === 0) { peg$fail(peg$c39); }
												}
											}
										} else {
											s7 = peg$FAILED;
										}
										if (s7 !== peg$FAILED) {
											if (input.substr(peg$currPos, 4) === peg$c40) {
												s8 = peg$c40;
												peg$currPos += 4;
											} else {
												s8 = peg$FAILED;
												if (peg$silentFails === 0) { peg$fail(peg$c41); }
											}
											if (s8 !== peg$FAILED) {
												peg$savedPos = s0;
												s1 = peg$c42(s3, s4, s7);
												s0 = s1;
											} else {
												peg$currPos = s0;
												s0 = peg$FAILED;
											}
										} else {
											peg$currPos = s0;
											s0 = peg$FAILED;
										}
									} else {
										peg$currPos = s0;
										s0 = peg$FAILED;
									}
								} else {
									peg$currPos = s0;
									s0 = peg$FAILED;
								}
							} else {
								peg$currPos = s0;
								s0 = peg$FAILED;
							}
						} else {
							peg$currPos = s0;
							s0 = peg$FAILED;
						}
					} else {
						peg$currPos = s0;
						s0 = peg$FAILED;
					}
				} else {
					peg$currPos = s0;
					s0 = peg$FAILED;
				}

				return s0;
			}

			function peg$parseHtmlAttribute() {
				var s0, s1, s2, s3, s4;

				s0 = peg$currPos;
				s1 = [];
				if (peg$c43.test(input.charAt(peg$currPos))) {
					s2 = input.charAt(peg$currPos);
					peg$currPos++;
				} else {
					s2 = peg$FAILED;
					if (peg$silentFails === 0) { peg$fail(peg$c44); }
				}
				if (s2 !== peg$FAILED) {
					while (s2 !== peg$FAILED) {
						s1.push(s2);
						if (peg$c43.test(input.charAt(peg$currPos))) {
							s2 = input.charAt(peg$currPos);
							peg$currPos++;
						} else {
							s2 = peg$FAILED;
							if (peg$silentFails === 0) { peg$fail(peg$c44); }
						}
					}
				} else {
					s1 = peg$FAILED;
				}
				if (s1 !== peg$FAILED) {
					if (input.charCodeAt(peg$currPos) === 61) {
						s2 = peg$c45;
						peg$currPos++;
					} else {
						s2 = peg$FAILED;
						if (peg$silentFails === 0) { peg$fail(peg$c46); }
					}
					if (s2 !== peg$FAILED) {
						s3 = peg$currPos;
						s4 = peg$parseQuotedString();
						if (s4 !== peg$FAILED) {
							peg$savedPos = s3;
							s4 = peg$c47(s1, s4);
						}
						s3 = s4;
						if (s3 !== peg$FAILED) {
							peg$savedPos = s0;
							s1 = peg$c48(s1, s3);
							s0 = s1;
						} else {
							peg$currPos = s0;
							s0 = peg$FAILED;
						}
					} else {
						peg$currPos = s0;
						s0 = peg$FAILED;
					}
				} else {
					peg$currPos = s0;
					s0 = peg$FAILED;
				}

				return s0;
			}

			function peg$parseQuotedString() {
				var s0, s1, s2, s3, s4;

				s0 = peg$currPos;
				if (input.charCodeAt(peg$currPos) === 34) {
					s1 = peg$c49;
					peg$currPos++;
				} else {
					s1 = peg$FAILED;
					if (peg$silentFails === 0) { peg$fail(peg$c50); }
				}
				if (s1 !== peg$FAILED) {
					s2 = peg$currPos;
					s3 = [];
					if (peg$c51.test(input.charAt(peg$currPos))) {
						s4 = input.charAt(peg$currPos);
						peg$currPos++;
					} else {
						s4 = peg$FAILED;
						if (peg$silentFails === 0) { peg$fail(peg$c52); }
					}
					while (s4 !== peg$FAILED) {
						s3.push(s4);
						if (peg$c51.test(input.charAt(peg$currPos))) {
							s4 = input.charAt(peg$currPos);
							peg$currPos++;
						} else {
							s4 = peg$FAILED;
							if (peg$silentFails === 0) { peg$fail(peg$c52); }
						}
					}
					if (s3 !== peg$FAILED) {
						peg$savedPos = s2;
						s3 = peg$c53(s3);
					}
					s2 = s3;
					if (s2 !== peg$FAILED) {
						if (input.charCodeAt(peg$currPos) === 34) {
							s3 = peg$c49;
							peg$currPos++;
						} else {
							s3 = peg$FAILED;
							if (peg$silentFails === 0) { peg$fail(peg$c50); }
						}
						if (s3 !== peg$FAILED) {
							peg$savedPos = s0;
							s1 = peg$c54(s2);
							s0 = s1;
						} else {
							peg$currPos = s0;
							s0 = peg$FAILED;
						}
					} else {
						peg$currPos = s0;
						s0 = peg$FAILED;
					}
				} else {
					peg$currPos = s0;
					s0 = peg$FAILED;
				}

				return s0;
			}

			function peg$parseMarkdownLink() {
				var s0, s1, s2, s3, s4, s5, s6;

				s0 = peg$currPos;
				if (input.charCodeAt(peg$currPos) === 91) {
					s1 = peg$c55;
					peg$currPos++;
				} else {
					s1 = peg$FAILED;
					if (peg$silentFails === 0) { peg$fail(peg$c56); }
				}
				if (s1 !== peg$FAILED) {
					s2 = [];
					if (peg$c57.test(input.charAt(peg$currPos))) {
						s3 = input.charAt(peg$currPos);
						peg$currPos++;
					} else {
						s3 = peg$FAILED;
						if (peg$silentFails === 0) { peg$fail(peg$c58); }
					}
					while (s3 !== peg$FAILED) {
						s2.push(s3);
						if (peg$c57.test(input.charAt(peg$currPos))) {
							s3 = input.charAt(peg$currPos);
							peg$currPos++;
						} else {
							s3 = peg$FAILED;
							if (peg$silentFails === 0) { peg$fail(peg$c58); }
						}
					}
					if (s2 !== peg$FAILED) {
						if (input.substr(peg$currPos, 2) === peg$c59) {
							s3 = peg$c59;
							peg$currPos += 2;
						} else {
							s3 = peg$FAILED;
							if (peg$silentFails === 0) { peg$fail(peg$c60); }
						}
						if (s3 !== peg$FAILED) {
							s4 = peg$currPos;
							s5 = [];
							if (peg$c61.test(input.charAt(peg$currPos))) {
								s6 = input.charAt(peg$currPos);
								peg$currPos++;
							} else {
								s6 = peg$FAILED;
								if (peg$silentFails === 0) { peg$fail(peg$c62); }
							}
							if (s6 !== peg$FAILED) {
								while (s6 !== peg$FAILED) {
									s5.push(s6);
									if (peg$c61.test(input.charAt(peg$currPos))) {
										s6 = input.charAt(peg$currPos);
										peg$currPos++;
									} else {
										s6 = peg$FAILED;
										if (peg$silentFails === 0) { peg$fail(peg$c62); }
									}
								}
							} else {
								s5 = peg$FAILED;
							}
							if (s5 !== peg$FAILED) {
								peg$savedPos = s4;
								s5 = peg$c63(s2, s5);
							}
							s4 = s5;
							if (s4 !== peg$FAILED) {
								if (input.charCodeAt(peg$currPos) === 41) {
									s5 = peg$c64;
									peg$currPos++;
								} else {
									s5 = peg$FAILED;
									if (peg$silentFails === 0) { peg$fail(peg$c65); }
								}
								if (s5 !== peg$FAILED) {
									peg$savedPos = s0;
									s1 = peg$c66(s2, s4);
									s0 = s1;
								} else {
									peg$currPos = s0;
									s0 = peg$FAILED;
								}
							} else {
								peg$currPos = s0;
								s0 = peg$FAILED;
							}
						} else {
							peg$currPos = s0;
							s0 = peg$FAILED;
						}
					} else {
						peg$currPos = s0;
						s0 = peg$FAILED;
					}
				} else {
					peg$currPos = s0;
					s0 = peg$FAILED;
				}

				return s0;
			}

			function peg$parseNewline() {
				var s0;

				if (peg$c67.test(input.charAt(peg$currPos))) {
					s0 = input.charAt(peg$currPos);
					peg$currPos++;
				} else {
					s0 = peg$FAILED;
					if (peg$silentFails === 0) { peg$fail(peg$c68); }
				}

				return s0;
			}

			peg$result = peg$startRuleFunction();

			if (peg$result !== peg$FAILED && peg$currPos === input.length) {
				return peg$result;
			} else {
				if (peg$result !== peg$FAILED && peg$currPos < input.length) {
					peg$fail(peg$endExpectation());
				}

				throw peg$buildStructuredError(
					peg$maxFailExpected,
					peg$maxFailPos < input.length ? input.charAt(peg$maxFailPos) : null,
					peg$maxFailPos < input.length
						? peg$computeLocation(peg$maxFailPos, peg$maxFailPos + 1)
						: peg$computeLocation(peg$maxFailPos, peg$maxFailPos)
				);
			}
		}

		return {
			SyntaxError: peg$SyntaxError,
			parse:       peg$parse
		};
	})();
